/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaApplication_final;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Hishan Kavishka
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
        Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Title3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_item_name = new javax.swing.JTextField();
        Title4 = new javax.swing.JLabel();
        txt_item_code = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Title5 = new javax.swing.JLabel();
        txt_item_price = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btn_clear = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        btn_save = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Title7 = new javax.swing.JLabel();
        btn_update_itemcode = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Title8 = new javax.swing.JLabel();
        btn_update_price = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btn_update = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        btn_update_clear = new javax.swing.JPanel();
        jLabel86 = new javax.swing.JLabel();
        Title2 = new javax.swing.JLabel();
        Title6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Title9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btn_close = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(41, 39, 40));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(41, 39, 40));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Title3.setForeground(new java.awt.Color(255, 255, 255));
        Title3.setText("Item Name :");
        jPanel2.add(Title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 430, 10));

        txt_item_name.setBackground(new java.awt.Color(41, 39, 40));
        txt_item_name.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        txt_item_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_item_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_item_name.setBorder(null);
        jPanel2.add(txt_item_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 430, 20));

        Title4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Title4.setForeground(new java.awt.Color(255, 255, 255));
        Title4.setText("Item Code :");
        jPanel2.add(Title4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 30));

        txt_item_code.setBackground(new java.awt.Color(41, 39, 40));
        txt_item_code.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        txt_item_code.setForeground(new java.awt.Color(255, 255, 255));
        txt_item_code.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_item_code.setBorder(null);
        jPanel2.add(txt_item_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 430, 20));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 430, 10));

        Title5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Title5.setForeground(new java.awt.Color(255, 255, 255));
        Title5.setText("Item Price(Rs) :");
        jPanel2.add(Title5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 140, 30));

        txt_item_price.setBackground(new java.awt.Color(41, 39, 40));
        txt_item_price.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        txt_item_price.setForeground(new java.awt.Color(255, 255, 255));
        txt_item_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_item_price.setBorder(null);
        txt_item_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_item_priceActionPerformed(evt);
            }
        });
        jPanel2.add(txt_item_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 430, 20));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 430, 10));

        btn_clear.setBackground(new java.awt.Color(41, 53, 65));
        btn_clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_clearMousePressed(evt);
            }
        });
        btn_clear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel83.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 24)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel83.setText("Clear");
        btn_clear.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 40));

        jPanel2.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 160, 60));

        btn_save.setBackground(new java.awt.Color(41, 53, 65));
        btn_save.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_saveMousePressed(evt);
            }
        });
        btn_save.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel84.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 24)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel84.setText("Save");
        btn_save.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 40));

        jPanel2.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 160, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 470, 620));

        jPanel3.setBackground(new java.awt.Color(41, 39, 40));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Title7.setForeground(new java.awt.Color(255, 255, 255));
        Title7.setText("Item Code :");
        jPanel3.add(Title7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 30));

        btn_update_itemcode.setBackground(new java.awt.Color(41, 39, 40));
        btn_update_itemcode.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        btn_update_itemcode.setForeground(new java.awt.Color(255, 255, 255));
        btn_update_itemcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn_update_itemcode.setBorder(null);
        jPanel3.add(btn_update_itemcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 620, 20));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 620, 10));

        Title8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Title8.setForeground(new java.awt.Color(255, 255, 255));
        Title8.setText("New Item Price :");
        jPanel3.add(Title8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 160, 30));

        btn_update_price.setBackground(new java.awt.Color(41, 39, 40));
        btn_update_price.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        btn_update_price.setForeground(new java.awt.Color(255, 255, 255));
        btn_update_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        btn_update_price.setBorder(null);
        jPanel3.add(btn_update_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 620, 20));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 620, 10));

        btn_update.setBackground(new java.awt.Color(41, 53, 65));
        btn_update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_updateMousePressed(evt);
            }
        });
        btn_update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel85.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 24)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(255, 255, 255));
        jLabel85.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel85.setText("Update");
        btn_update.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 40));

        jPanel3.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 160, 60));

        btn_update_clear.setBackground(new java.awt.Color(41, 53, 65));
        btn_update_clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_update_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_update_clearMousePressed(evt);
            }
        });
        btn_update_clear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel86.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 24)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(255, 255, 255));
        jLabel86.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel86.setText("Clear");
        btn_update_clear.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 40));

        jPanel3.add(btn_update_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 160, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 660, 270));

        Title2.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        Title2.setForeground(new java.awt.Color(255, 255, 255));
        Title2.setText("Update Item Price");
        jPanel1.add(Title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 180, 30));

        Title6.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        Title6.setForeground(new java.awt.Color(255, 255, 255));
        Title6.setText("Add New Item");
        jPanel1.add(Title6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, 30));

        jPanel4.setBackground(new java.awt.Color(41, 39, 40));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title9.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Title9.setForeground(new java.awt.Color(255, 255, 255));
        Title9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title9.setText("Future Developments");
        jPanel4.add(Title9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 660, 70));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 660, 330));

        jPanel5.setBackground(new java.awt.Color(178, 8, 55));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaApplication_final/Icons/Cancel_38px.png"))); // NOI18N
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_closeMousePressed(evt);
            }
        });
        jPanel5.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, -1, 48));

        Title1.setFont(new java.awt.Font("Montserrat Subrayada", 1, 55)); // NOI18N
        Title1.setForeground(new java.awt.Color(255, 255, 255));
        Title1.setText("Settings");
        jPanel5.add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 310, 50));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMousePressed
        Mew_MainMenu main=new Mew_MainMenu();
        main.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_closeMousePressed

    private void btn_clearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMousePressed
        txt_item_name.setText("");
        txt_item_code.setText("");
        txt_item_price.setText("");
        
    }//GEN-LAST:event_btn_clearMousePressed

    private void btn_saveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMousePressed
            Connection con = null;
            SQlConnection a= new SQlConnection();
                try{
                con = a.connect();
                String sql="INSERT INTO `products`(`item`, `itemcode`,`price`) VALUES (?,?,?)";
                PreparedStatement pst=con.prepareStatement(sql);
                pst.setString(1,txt_item_name.getText());
                pst.setString(2,txt_item_code.getText());
                pst.setString(3,txt_item_price.getText());
                pst.executeUpdate();
                pst.close();
                con.close();
                
                //Clear Text Boxes
                txt_item_name.setText("");
                txt_item_code.setText("");
                txt_item_price.setText("");
                
                //Show Success Message box
                JOptionPane.showMessageDialog(null,"Successfully Added Data To The System");
            }

            catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null,"Use Another Item Number. , Your Item Number is Alredy In The System");
                
            }
    }//GEN-LAST:event_btn_saveMousePressed

    private void btn_updateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMousePressed
            Connection con = null;
            SQlConnection a= new SQlConnection();
                try{
                con = a.connect();
                String sql="UPDATE `products` SET `price`=? WHERE `itemcode`=?";
                PreparedStatement pst=con.prepareStatement(sql);
                pst.setString(1,btn_update_price.getText());
                pst.setString(2,btn_update_itemcode.getText());
                pst.executeUpdate();
                pst.close();
                con.close();
                
                //Clear Text Boxes
                btn_update_price.setText("");
                btn_update_itemcode.setText("");
                
                //Show Success Message box
                JOptionPane.showMessageDialog(null,"Successfully Updated Data To The System");
            }

            catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null,"Insert Only Numbers On Price Field");
                
            }
        
        
    }//GEN-LAST:event_btn_updateMousePressed

    private void btn_update_clearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_update_clearMousePressed
        btn_update_price.setText("");
        btn_update_itemcode.setText("");
    }//GEN-LAST:event_btn_update_clearMousePressed

    private void txt_item_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_item_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_item_priceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title3;
    private javax.swing.JLabel Title4;
    private javax.swing.JLabel Title5;
    private javax.swing.JLabel Title6;
    private javax.swing.JLabel Title7;
    private javax.swing.JLabel Title8;
    private javax.swing.JLabel Title9;
    private javax.swing.JPanel btn_clear;
    private javax.swing.JLabel btn_close;
    private javax.swing.JPanel btn_save;
    private javax.swing.JPanel btn_update;
    private javax.swing.JPanel btn_update_clear;
    private javax.swing.JTextField btn_update_itemcode;
    private javax.swing.JTextField btn_update_price;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField txt_item_code;
    private javax.swing.JTextField txt_item_name;
    private javax.swing.JTextField txt_item_price;
    // End of variables declaration//GEN-END:variables
}
