/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaApplication_final;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Hishan Kavishka
 */
public class users extends javax.swing.JFrame {
    String s;
    
    

    /**
     * Creates new form users
     */
    public users() {
        initComponents();
         Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        
        Connection con = null;
        SQlConnection a= new SQlConnection();
        try{
            con = a.connect();
            Statement st=con.createStatement();
            String sql="SELECT * FROM login WHERE `sno`='"+current+"'";
            
            ResultSet rs=st.executeQuery(sql);
            if(rs.next()){
            
                byte[] img = rs.getBytes("Image");
                
                ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImg = im.getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImg);
                lbl_image.setIcon(newImage);
                
            }
            else{
                    JOptionPane.showMessageDialog(null, "No Data");
                    
            }
            String status=rs.getString("username");
            lbl_Realtime_username.setText("..Hello "+status+"..");
                  
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            //String status=rs.getString("username");
            //lbl_Realtime_username.setText("..Hello "+status+"..");
        }
                
        
          
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Objects = new javax.swing.JPanel();
        btn_user = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        btn_report = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        btn_home = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        btn_settings = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_username111 = new javax.swing.JLabel();
        lbl_username2 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Cancel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbl_username1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_username4 = new javax.swing.JLabel();
        txt_repassword = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lbl_username6 = new javax.swing.JLabel();
        txt_Enum = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        txt_blood = new javax.swing.JTextField();
        lbl_username7 = new javax.swing.JLabel();
        lbl_username8 = new javax.swing.JLabel();
        txt_phonenum = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        lbl_username9 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        txt_address = new javax.swing.JTextField();
        lbl_username10 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        txt_email = new javax.swing.JTextField();
        lbl_username5 = new javax.swing.JLabel();
        Cancel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_newpassword = new javax.swing.JTextField();
        lbl_address = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        lbl_reenterpassword = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_phone = new javax.swing.JLabel();
        lbl_emgphone = new javax.swing.JLabel();
        lbl_blood = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_image = new javax.swing.JLabel();
        lbl_Realtime_username = new javax.swing.JLabel();
        btn_image = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(41, 39, 40));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Objects.setBackground(new java.awt.Color(41, 39, 40));
        Objects.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))));

        btn_user.setBackground(new java.awt.Color(41, 53, 65));
        btn_user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_userMousePressed(evt);
            }
        });
        btn_user.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hishan\\Desktop\\java\\Icons\\User Account_60px.png")); // NOI18N
        btn_user.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 60, 64));

        jLabel41.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Account");
        btn_user.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel60.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("User");
        btn_user.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        btn_report.setBackground(new java.awt.Color(41, 39, 40));
        btn_report.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_reportMousePressed(evt);
            }
        });
        btn_report.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hishan\\Desktop\\java\\Icons\\Doughnut Chart_60px.png")); // NOI18N
        btn_report.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 60, 64));

        jLabel43.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Report");
        btn_report.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel63.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Daily");
        btn_report.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        btn_home.setBackground(new java.awt.Color(41, 39, 40));
        btn_home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_homeMousePressed(evt);
            }
        });
        btn_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hishan\\Desktop\\java\\Icons\\Home_48px.png")); // NOI18N
        btn_home.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 53, 64));

        jLabel55.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Home");
        btn_home.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        btn_settings.setBackground(new java.awt.Color(41, 39, 40));
        btn_settings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_settingsMousePressed(evt);
            }
        });
        btn_settings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel57.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hishan\\Desktop\\java\\Icons\\settings_48px.png")); // NOI18N
        btn_settings.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 64));

        jLabel59.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 20)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText(" Settings");
        btn_settings.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        javax.swing.GroupLayout ObjectsLayout = new javax.swing.GroupLayout(Objects);
        Objects.setLayout(ObjectsLayout);
        ObjectsLayout.setHorizontalGroup(
            ObjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_report, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_settings, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
            .addComponent(btn_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ObjectsLayout.setVerticalGroup(
            ObjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ObjectsLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_report, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_user, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_settings, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jPanel1.add(Objects, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(41, 39, 40));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_username111.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_username111.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username111.setText("Username");
        jPanel2.add(lbl_username111, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 90, 20));

        lbl_username2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_username2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username2.setText("New Password");
        jPanel2.add(lbl_username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 140, -1));

        txt_username.setBackground(new java.awt.Color(41, 39, 40));
        txt_username.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_username.setBorder(null);
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_usernameKeyReleased(evt);
            }
        });
        jPanel2.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 240, 30));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 240, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 240, 10));

        Cancel1.setBackground(new java.awt.Color(41, 53, 65));
        Cancel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Cancel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Cancel1MousePressed(evt);
            }
        });
        Cancel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Save Information");
        Cancel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 20));

        jPanel2.add(Cancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 740, 470, 40));

        lbl_username1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        lbl_username1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username1.setText("Additional Information");
        jPanel2.add(lbl_username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 290, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hishan\\Desktop\\java\\Icons\\Cancel_38px.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 40, -1));

        lbl_username4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_username4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username4.setText("Re-enter Password");
        jPanel2.add(lbl_username4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 160, 30));

        txt_repassword.setBackground(new java.awt.Color(41, 39, 40));
        txt_repassword.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_repassword.setForeground(new java.awt.Color(255, 255, 255));
        txt_repassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_repassword.setBorder(null);
        txt_repassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_repasswordActionPerformed(evt);
            }
        });
        txt_repassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_repasswordKeyReleased(evt);
            }
        });
        jPanel2.add(txt_repassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 240, 20));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 240, 10));

        lbl_username6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_username6.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username6.setText("Phone Number");
        jPanel2.add(lbl_username6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 140, -1));

        txt_Enum.setBackground(new java.awt.Color(41, 39, 40));
        txt_Enum.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_Enum.setForeground(new java.awt.Color(255, 255, 255));
        txt_Enum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Enum.setBorder(null);
        txt_Enum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EnumActionPerformed(evt);
            }
        });
        txt_Enum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_EnumKeyReleased(evt);
            }
        });
        jPanel2.add(txt_Enum, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 250, 20));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 600, 250, 10));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 650, 250, 10));

        txt_blood.setBackground(new java.awt.Color(41, 39, 40));
        txt_blood.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_blood.setForeground(new java.awt.Color(255, 255, 255));
        txt_blood.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_blood.setBorder(null);
        txt_blood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bloodActionPerformed(evt);
            }
        });
        txt_blood.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_bloodKeyReleased(evt);
            }
        });
        jPanel2.add(txt_blood, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 630, 250, 20));

        lbl_username7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_username7.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username7.setText("Blood Group");
        jPanel2.add(lbl_username7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, 140, -1));

        lbl_username8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_username8.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username8.setText("Emergency Number");
        jPanel2.add(lbl_username8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 170, -1));

        txt_phonenum.setBackground(new java.awt.Color(41, 39, 40));
        txt_phonenum.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_phonenum.setForeground(new java.awt.Color(255, 255, 255));
        txt_phonenum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_phonenum.setBorder(null);
        txt_phonenum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phonenumActionPerformed(evt);
            }
        });
        txt_phonenum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_phonenumKeyReleased(evt);
            }
        });
        jPanel2.add(txt_phonenum, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 250, 20));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 250, 10));

        lbl_username9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_username9.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username9.setText("Home Address");
        jPanel2.add(lbl_username9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 680, 140, -1));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 700, 250, 10));

        txt_address.setBackground(new java.awt.Color(41, 39, 40));
        txt_address.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_address.setForeground(new java.awt.Color(255, 255, 255));
        txt_address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_address.setBorder(null);
        txt_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addressActionPerformed(evt);
            }
        });
        txt_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_addressKeyReleased(evt);
            }
        });
        jPanel2.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 680, 250, 20));

        lbl_username10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_username10.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username10.setText("Email Address");
        jPanel2.add(lbl_username10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 140, -1));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 250, 10));

        txt_email.setBackground(new java.awt.Color(41, 39, 40));
        txt_email.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        txt_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_email.setBorder(null);
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_emailKeyReleased(evt);
            }
        });
        jPanel2.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 250, 20));

        lbl_username5.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        lbl_username5.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username5.setText("User Accounts Settings");
        jPanel2.add(lbl_username5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 290, 60));

        Cancel3.setBackground(new java.awt.Color(41, 53, 65));
        Cancel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Cancel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Cancel3MousePressed(evt);
            }
        });
        Cancel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("UPDATE");
        Cancel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 80, 20));

        jPanel2.add(Cancel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 470, 40));

        txt_newpassword.setBackground(new java.awt.Color(41, 39, 40));
        txt_newpassword.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 20)); // NOI18N
        txt_newpassword.setForeground(new java.awt.Color(255, 255, 255));
        txt_newpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_newpassword.setBorder(null);
        txt_newpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_newpasswordActionPerformed(evt);
            }
        });
        txt_newpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_newpasswordKeyReleased(evt);
            }
        });
        jPanel2.add(txt_newpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 240, 30));

        lbl_address.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_address.setForeground(new java.awt.Color(255, 0, 0));
        lbl_address.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 700, 250, 20));

        lbl_username.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 0, 0));
        lbl_username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbl_usernameKeyReleased(evt);
            }
        });
        jPanel2.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 240, 20));

        lbl_password.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(255, 0, 0));
        lbl_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 240, 20));

        lbl_reenterpassword.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_reenterpassword.setForeground(new java.awt.Color(255, 0, 0));
        lbl_reenterpassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl_reenterpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 240, 20));

        lbl_email.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(255, 0, 0));
        lbl_email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 250, 20));

        lbl_phone.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_phone.setForeground(new java.awt.Color(255, 0, 0));
        lbl_phone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 250, 20));

        lbl_emgphone.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_emgphone.setForeground(new java.awt.Color(255, 0, 0));
        lbl_emgphone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl_emgphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 600, 250, 20));

        lbl_blood.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_blood.setForeground(new java.awt.Color(255, 0, 0));
        lbl_blood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbl_blood, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 650, 250, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 610, 830));

        jPanel3.setBackground(new java.awt.Color(41, 39, 40));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaApplication_final/Icons/user01.png"))); // NOI18N
        lbl_image.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel3.add(lbl_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 280, 260));

        lbl_Realtime_username.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_Realtime_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Realtime_username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Realtime_username.setText("..Hello");
        jPanel3.add(lbl_Realtime_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 370, 70));

        btn_image.setBackground(new java.awt.Color(41, 53, 65));
        btn_image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_imageMousePressed(evt);
            }
        });
        btn_image.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Update Profile Picture");
        btn_image.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 20));

        jPanel3.add(btn_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, 250, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 630, 830));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyReleased
        // TODO add your handling code here:
        lbl_username.setText("");
    }//GEN-LAST:event_txt_usernameKeyReleased

    private void Cancel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cancel1MousePressed
        // TODO add your handling code here:
        if(txt_email.getText().trim().isEmpty()||txt_phonenum.getText().trim().isEmpty()||txt_Enum.getText().trim().isEmpty()||txt_blood.getText().trim().isEmpty()||txt_address.getText().trim().isEmpty()){
            
            lbl_email.setText(common);
            lbl_phone.setText(common);
            lbl_emgphone.setText(common);
            lbl_blood.setText(common);
            lbl_address.setText(common);
            
        }
        else{
            Connection con = null;
            SQlConnection a= new SQlConnection();
            try{
            String email=txt_email.getText();
            int phone=Integer.parseInt(txt_phonenum.getText());
            int emgphone=Integer.parseInt(txt_Enum.getText());
            String blood=txt_blood.getText();
            String address=txt_address.getText();
            
            con = a.connect();
            String sql="UPDATE `login` SET `Email`=?,`phone`=?,`emgphone`=?,`blood`=?,`address`=? WHERE `sno`=?";
            PreparedStatement pst=con.prepareStatement(sql);
            
            pst.setString(1,email);
            pst.setInt(2, phone);
            pst.setInt(3, emgphone);
            pst.setString(4,blood);
            pst.setString(5,address);
            pst.setInt(6, current);
            
            
            
            pst.executeUpdate();
            con.close();
            
            txt_email.setText("");
            txt_phonenum.setText("");
            txt_Enum.setText("");
            txt_blood.setText("");
            txt_address.setText("");
            
            JOptionPane.showMessageDialog(null,"Data inserted");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
        
        
        
        
        
    }//GEN-LAST:event_Cancel1MousePressed

    private void btn_userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_userMousePressed
        // TODO add your handling code here:
        a.setColor(btn_user);
        a.resetColor(btn_report);
        a.resetColor(btn_home);
        a.resetColor(btn_settings);
    }//GEN-LAST:event_btn_userMousePressed

    private void btn_reportMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reportMousePressed
        // TODO add your handling code here:
        a.setColor(btn_report);
        a.resetColor(btn_home);
        a.resetColor(btn_user);
        a.resetColor(btn_settings);
        
        Report a=new Report();
        a.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_reportMousePressed

    private void btn_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMousePressed
        // TODO add your handling code here:
        a.setColor(btn_home);
        a.resetColor(btn_report);
        a.resetColor(btn_user);
        a.resetColor(btn_settings);
        
        Mew_MainMenu a=new Mew_MainMenu();
        a.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_homeMousePressed

    private void btn_settingsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_settingsMousePressed
        // TODO add your handling code here:
        a.setColor(btn_settings);
        a.resetColor(btn_report);
        a.resetColor(btn_user);
        a.resetColor(btn_home);
        
        Settings settings=new Settings();
        settings.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_settingsMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MousePressed

    private void btn_imageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_imageMousePressed
        // TODO add your handling code here:
        
        try{
            JFileChooser fileChooser=new JFileChooser();
            fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
            FileNameExtensionFilter filter=new FileNameExtensionFilter("*.IMAGE","jpg","gif","png");
            fileChooser.addChoosableFileFilter(filter);
            int result=fileChooser.showSaveDialog(null);
        
            if(result==JFileChooser.APPROVE_OPTION){
                File selectedFile=fileChooser.getSelectedFile();
                String path=selectedFile.getAbsolutePath();
                lbl_image.setIcon(ResizeImage(path));
                s=path;
            }
            else if(result == JFileChooser.CANCEL_OPTION){
                JOptionPane.showMessageDialog(null,"No Data");
            }
            Connection con = null;
            SQlConnection a= new SQlConnection();
            try{
                con = a.connect();
                String sql="UPDATE `login` SET `image`=? WHERE `sno`=?";
                PreparedStatement pst=con.prepareStatement(sql);
                InputStream is=new FileInputStream(new File(s));
                
                pst.setBlob(1, is);
                pst.setInt(2, current);
                
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data inserted");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
            
            
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        
        
    }//GEN-LAST:event_btn_imageMousePressed

    private void txt_repasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_repasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_repasswordActionPerformed

    private void txt_repasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_repasswordKeyReleased
        // TODO add your handling code here:
        lbl_reenterpassword.setText("");
    }//GEN-LAST:event_txt_repasswordKeyReleased

    private void txt_EnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EnumActionPerformed

    private void txt_EnumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_EnumKeyReleased
        // TODO add your handling code here:
        lbl_emgphone.setText("");
    }//GEN-LAST:event_txt_EnumKeyReleased

    private void txt_bloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bloodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bloodActionPerformed

    private void txt_bloodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bloodKeyReleased
        // TODO add your handling code here:
        lbl_blood.setText("");
    }//GEN-LAST:event_txt_bloodKeyReleased

    private void txt_phonenumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phonenumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phonenumActionPerformed

    private void txt_phonenumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phonenumKeyReleased
        // TODO add your handling code here:
        lbl_phone.setText("");
    }//GEN-LAST:event_txt_phonenumKeyReleased

    private void txt_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressActionPerformed

    private void txt_addressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_addressKeyReleased
        // TODO add your handling code here:
        lbl_address.setText("");
    }//GEN-LAST:event_txt_addressKeyReleased

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyReleased
        // TODO add your handling code here:
        lbl_email.setText("");
    }//GEN-LAST:event_txt_emailKeyReleased

    private void Cancel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cancel3MousePressed
        // TODO add your handling code here:
            
            if(txt_username.getText().trim().isEmpty()||txt_newpassword.getText().trim().isEmpty()||txt_repassword.getText().trim().isEmpty()){                
                if(txt_username.getText().trim().isEmpty()||txt_newpassword.getText().trim().isEmpty()){
                    if(txt_username.getText().trim().isEmpty()){
                        lbl_username.setText(common);
                        lbl_password.setText(common);
                        lbl_reenterpassword.setText(common);
                    }
                    else{
                        lbl_password.setText(common);
                        lbl_reenterpassword.setText(common);
                    }
                }
                else{
                    lbl_reenterpassword.setText(common);
                }
            }
            else{
                
                
                
                if(txt_newpassword.getText().equals(txt_repassword.getText())){
                   
                   
                    Connection con = null;
                    SQlConnection a= new SQlConnection();
                    try{
                        String user=txt_username.getText();
                        String pass=txt_newpassword.getText();
            
                        con = a.connect();
                        String sql="UPDATE `login` SET `username`=?,`password`=? WHERE `sno`=?";
                        PreparedStatement pst=con.prepareStatement(sql);
                         
                       
                        pst.setString(1,user);
                        pst.setString(2,pass);
                        pst.setInt(3, current);
            
                        pst.executeUpdate();
                        con.close();
                        
                        txt_username.setText("");
                        txt_newpassword.setText("");
                        txt_repassword.setText("");
                        
                        JOptionPane.showMessageDialog(null,"Data inserted");
                    }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(null,e);
                    }
                }
                else{
                    String info="Password Mismatch";
                    lbl_password.setText(info);
                    lbl_reenterpassword.setText(info);       
                }
            }
        
        
        
        
        
        
    }//GEN-LAST:event_Cancel3MousePressed

    private void txt_newpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_newpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_newpasswordActionPerformed

    private void txt_newpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_newpasswordKeyReleased
        // TODO add your handling code here:
        lbl_password.setText("");
    }//GEN-LAST:event_txt_newpasswordKeyReleased

    private void lbl_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_usernameKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lbl_usernameKeyReleased
//##### Importing Color Changes to Side Panel Buttons
    ChangeButtonColor a=new ChangeButtonColor();

//Get Current User
    int snumber;
    current_user x=new current_user();
    int current=x.current(snumber);
    
    
    String common="Please Enter data";
    
    public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new users().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cancel1;
    private javax.swing.JPanel Cancel3;
    private javax.swing.JPanel Objects;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_image;
    private javax.swing.JPanel btn_report;
    private javax.swing.JPanel btn_settings;
    private javax.swing.JPanel btn_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbl_Realtime_username;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_blood;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_emgphone;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_phone;
    private javax.swing.JLabel lbl_reenterpassword;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLabel lbl_username1;
    private javax.swing.JLabel lbl_username10;
    private javax.swing.JLabel lbl_username111;
    private javax.swing.JLabel lbl_username2;
    private javax.swing.JLabel lbl_username4;
    private javax.swing.JLabel lbl_username5;
    private javax.swing.JLabel lbl_username6;
    private javax.swing.JLabel lbl_username7;
    private javax.swing.JLabel lbl_username8;
    private javax.swing.JLabel lbl_username9;
    private javax.swing.JTextField txt_Enum;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_blood;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_newpassword;
    private javax.swing.JTextField txt_phonenum;
    private javax.swing.JTextField txt_repassword;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
